import { promises as fs } from "node:fs";
import path from "node:path";
import ts from "typescript";

const roots = ["app", "components", "lib"];
const korean = /[가-힣]/;
const strings = new Set();
const observedRuntimeWords = ["가이드","간","감지된","개","건부터","경기","고급","공식","과","관리자","관측","권총","기능","기본","기준","내용은","년","다수","다이","단발","대표하지","데이터","도감","등","때는","또는","라이드","론도","맵","모으는","목록과","반영됩니다","반영합니다","방","배틀스탯","변경","별","비공식","비밀의","살펴","상상력","상위권","상자","서비스가","서비스입니다","세팅이","수집","순위를","순위에","스펙","스펙과","스펙에","승인","시야","시점","실전","실제","실험실","쌓이면","아닙니다","안정","않는","애니메이션","약","오어","은폐","의","이","이력","이론","이상이","이용자를","이펙트","이후","자동","자동으로","장착","적용일","적을","전","전리품","전체","정리했습니다","정보","정보로","조합","주세요","중급","중입니다","지속","참고용","초기","총구","총기","총성과","최근","추가","추천","추천보다","충분히","캘리버","코스믹","키퍼","킬","킬피드","타임","탄","탄두","탄속","탄창","통계","파츠","패치","패치노트","표본","표본을","표본이","표본입니다","표시합니다","풀가동","프라이팬","피해량","한","함께","해석해","헤비","현재","현행","화면","화면에","화염","확인된","후","흔들림"];

async function collectFiles(directory) {
  const entries = await fs.readdir(directory, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const target = path.join(directory, entry.name);
    if (entry.isDirectory()) files.push(...await collectFiles(target));
    else if (/\.(ts|tsx)$/.test(entry.name) && entry.name !== "generatedTranslations.ts") files.push(target);
  }
  return files;
}

function add(value) {
  const clean = value.replace(/\s+/g, " ").trim();
  if (clean && clean.length <= 600 && korean.test(clean)) {
    strings.add(clean);
    clean.match(/[가-힣]+/g)?.forEach((word) => strings.add(word));
  }
}

for (const root of roots) {
  for (const file of await collectFiles(root)) {
    const source = await fs.readFile(file, "utf8");
    const tree = ts.createSourceFile(file, source, ts.ScriptTarget.Latest, true, file.endsWith("x") ? ts.ScriptKind.TSX : ts.ScriptKind.TS);
    function visit(node) {
      if (ts.isStringLiteralLike(node) || ts.isJsxText(node) || ts.isTemplateHead(node) || ts.isTemplateMiddle(node) || ts.isTemplateTail(node)) add(node.text);
      ts.forEachChild(node, visit);
    }
    visit(tree);
  }
}
observedRuntimeWords.forEach((word) => strings.add(word));

async function translate(value) {
  const query = new URLSearchParams({ client: "gtx", sl: "ko", tl: "en", dt: "t", q: value });
  for (let attempt = 0; attempt < 5; attempt += 1) {
    const response = await fetch(`https://translate.googleapis.com/translate_a/single?${query}`);
    if (response.ok) {
      const data = await response.json();
      return data[0].map((part) => part[0]).join("").trim();
    }
    if (attempt === 4) throw new Error(`Translation failed (${response.status}): ${value}`);
    await new Promise((resolve) => setTimeout(resolve, 500 * (attempt + 1)));
  }
}

const sourceStrings = [...strings].sort((a, b) => a.localeCompare(b, "ko"));
const translated = new Array(sourceStrings.length);
let cursor = 0;

async function worker() {
  while (cursor < sourceStrings.length) {
    const index = cursor++;
    translated[index] = await translate(sourceStrings[index]);
  }
}

await Promise.all(Array.from({ length: 3 }, worker));

const entries = sourceStrings.map((source, index) => `  ${JSON.stringify(source)}: ${JSON.stringify(translated[index])},`).join("\n");
const output = `// Generated by scripts/generate_translations.mjs.\nexport const generatedTranslations: Record<string, string> = {\n${entries}\n};\n`;
await fs.writeFile("components/generatedTranslations.ts", output, "utf8");
console.log(`Generated ${sourceStrings.length} translations.`);
